import React, { useState } from 'react';
import { Search, Printer, UserPlus, Save, Camera, Plus, Minus, X, Laptop, Monitor, Gamepad2, Layers, ClipboardCheck, Lock, AlertCircle, RotateCcw, ShieldCheck, HeartPulse } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { motion, AnimatePresence } from 'framer-motion';
import { Camera as CapCamera, CameraResultType, CameraSource } from '@capacitor/camera';
import TermsModal from '../components/TermsModal';
import ThermalLabel from '../components/ThermalLabel';
import { localDB } from '../lib/db';

interface Customer {
    id: string;
    full_name: string;
    phone: string;
    email?: string;
}

const IntakePage: React.FC = () => {
    const [phone, setPhone] = useState('');
    const [fullName, setFullName] = useState('');
    const [customer, setCustomer] = useState<Customer | null>(null);
    const [device, setDevice] = useState({
        type: 'Laptop',
        brand: '',
        model: '',
        serial: '',
        color: ''
    });
    const [password, setPassword] = useState('');
    const [probing, setProbing] = useState({
        occurrence: '',
        previousRepair: 'No',
        troubleshooting: ''
    });
    const [faults, setFaults] = useState<string[]>([]);
    const [otherFault, setOtherFault] = useState('');
    const [accessories, setAccessories] = useState<string[]>([]);
    const [customAccessory, setCustomAccessory] = useState('');
    const [photos, setPhotos] = useState<string[]>([]);
    const [isSaving, setIsSaving] = useState(false);
    const [stickerCount, setStickerCount] = useState(1);
    const [showTerms, setShowTerms] = useState(false);
    const [isFastTrack, setIsFastTrack] = useState(false);
    const [csTroubleshooting, setCsTroubleshooting] = useState<string[]>([]);

    // Auto-generated ticket number for UI, real one generated by DB
    const [tempTicketId] = useState('TKT-' + (Math.random() * 9000 + 1000).toFixed(0));

    const deviceTypes = [
        { name: 'Laptop', icon: <Laptop size={18} /> },
        { name: 'Desktop', icon: <Monitor size={18} /> },
        { name: 'Console', icon: <Gamepad2 size={18} /> },
        { name: 'Others', icon: <Layers size={18} /> }
    ];

    const csBestPractices = [
        'Hard Reset (Static Discharge)', 'Test with Shop Adapter',
        'External Display Output', 'Battery Isolation',
        'Flashlight Test (Dim LCD)', 'CMOS/RTC Recovery'
    ];

    const commonFaults = [
        'No power', 'Overheating', 'Bluescreen',
        'No Display', 'LCD Flicker', 'LCD Crack',
        'Not Charging', 'Sudden Shutdown'
    ];

    const commonAccessories = ['Charger', 'USB', 'Bag', 'Mouse', 'Keyboard'];

    const handleLookup = async () => {
        if (phone.length < 5) return;
        const { data, error } = await supabase
            .from('customers')
            .select('*')
            .eq('phone', phone)
            .maybeSingle();

        if (error) console.error("Lookup error:", error);

        if (data) {
            setCustomer(data);
            setFullName(data.full_name);
        } else {
            setCustomer(null);
        }
    };

    const toggleItem = (setList: React.Dispatch<React.SetStateAction<string[]>>, item: string) => {
        setList(prev => prev.includes(item) ? prev.filter(i => i !== item) : [...prev, item]);
    };

    const takePhoto = async () => {
        try {
            const image = await CapCamera.getPhoto({
                quality: 90,
                allowEditing: false,
                resultType: CameraResultType.Uri,
                source: CameraSource.Camera
            });
            if (image.webPath) {
                setPhotos(prev => [...prev, image.webPath!]);
            }
        } catch (e) {
            console.error('Camera cancelled or failed', e);
        }
    };

    const removePhoto = (index: number) => {
        setPhotos(prev => prev.filter((_, i) => i !== index));
    };

    const handleSubmit = async () => {
        setShowTerms(false);
        setIsSaving(true);

        try {
            // --- PHOTO UPLOAD SUB-ROUTINE ---
            const uploadedUrls = [];
            for (const localUri of photos) {
                if (localUri.startsWith('http')) { // Already uploaded or webPath
                    const response = await fetch(localUri);
                    const blob = await response.blob();
                    const fileName = `${Date.now()}-${Math.random().toString(36).substring(7)}.jpg`;
                    const { data, error } = await supabase.storage
                        .from('repair-photos')
                        .upload(fileName, blob);

                    if (data) {
                        const { data: { publicUrl } } = supabase.storage
                            .from('repair-photos')
                            .getPublicUrl(data.path);
                        uploadedUrls.push(publicUrl);
                    }
                }
            }

            let customerId = customer?.id;

            if (!navigator.onLine) {
                // --- OFFLINE ROUTING ---
                const tempId = `temp-cust-${Date.now()}`;
                customerId = customerId || tempId;

                // Queue Customer
                if (!customer?.id) {
                    await localDB.syncQueue.add({ action: 'insert', table: 'customers', payload: { id: customerId, phone, full_name: fullName || 'Walk-in Customer' }, status: 'pending', created_at: Date.now() });
                } else if (customer && fullName && customer.full_name !== fullName) {
                    await localDB.syncQueue.add({ action: 'update', table: 'customers', payload: { id: customerId, full_name: fullName }, status: 'pending', created_at: Date.now() });
                }

                // Queue Device
                const deviceId = `temp-dev-${Date.now()}`;
                await localDB.syncQueue.add({ action: 'insert', table: 'devices', payload: { id: deviceId, customer_id: customerId, brand: device.brand, model: device.model, serial_number: device.serial, color: device.color, device_type: device.type }, status: 'pending', created_at: Date.now() });

                // Queue Ticket
                const ticketStatus = isFastTrack ? 'Checking' : 'Pending';
                const probingData = { occurrence: probing.occurrence, previousRepair: probing.previousRepair, troubleshooting: probing.troubleshooting, cs_best_practices: csTroubleshooting, faults: faults };
                await localDB.syncQueue.add({ action: 'insert', table: 'repair_tickets', payload: { customer_id: customerId, device_id: deviceId, device_password: password, probing_history: probingData, accessories: accessories, photos: photos, status: ticketStatus, priority: isFastTrack ? 'High' : 'Medium' }, status: 'pending', created_at: Date.now() });

                setTimeout(() => {
                    window.print();
                    alert(`OFFLINE MODE: Network down. Ticket securely queued in Local Cache.\nIt will auto-sync to Cloud when internet is restored.\n\nPrinting Temporary Sticker...`);
                    setPhone(''); setFullName(''); setCustomer(null); setDevice({ type: 'Laptop', brand: '', model: '', serial: '', color: '' }); setPassword(''); setProbing({ occurrence: '', previousRepair: 'No', troubleshooting: '' }); setFaults([]); setAccessories([]); setPhotos([]); setCsTroubleshooting([]);
                }, 500);

                setIsSaving(false);
                return;
            }

            // --- ONLINE ROUTING ---
            // 1. Upsert Customer
            if (!customerId) {
                // Fallback check: just in case they didn't trigger the onBlur lookup
                const { data: existingCust } = await supabase
                    .from('customers')
                    .select('id, full_name')
                    .eq('phone', phone)
                    .maybeSingle();

                if (existingCust) {
                    customerId = existingCust.id;
                    if (fullName && existingCust.full_name !== fullName) {
                        await supabase.from('customers').update({ full_name: fullName }).eq('id', customerId);
                    }
                } else {
                    // Try to insert
                    const { data: newCust, error: custErr } = await supabase
                        .from('customers')
                        .insert([{ phone, full_name: fullName || 'Walk-in Customer' }])
                        .select()
                        .single();

                    if (custErr) {
                        // One final fallback if insert hits unique constraint at the exact same microsecond
                        if (custErr.code === '23505') {
                            const { data: duplicateCust } = await supabase.from('customers').select('id').eq('phone', phone).single();
                            if (duplicateCust) customerId = duplicateCust.id;
                        } else {
                            throw custErr;
                        }
                    } else {
                        customerId = newCust.id;
                    }
                }
            } else if (customer && fullName && customer.full_name !== fullName) {
                // Update existing customer name if changed
                await supabase.from('customers').update({ full_name: fullName }).eq('id', customerId);
            }

            // 2. Insert Device
            const { data: newDevice, error: devErr } = await supabase
                .from('devices')
                .insert([{
                    customer_id: customerId,
                    brand: device.brand,
                    model: device.model,
                    serial_number: device.serial,
                    color: device.color,
                    device_type: device.type
                }])
                .select()
                .single();

            if (devErr) throw devErr;

            // 3. Insert Repair Ticket
            const ticketStatus = isFastTrack ? 'Checking' : 'Pending';
            const probingData = {
                occurrence: probing.occurrence,
                previousRepair: probing.previousRepair,
                troubleshooting: probing.troubleshooting,
                cs_best_practices: csTroubleshooting,
                faults: faults
            };

            const { data: newTicket, error: ticketErr } = await supabase
                .from('repair_tickets')
                .insert([{
                    customer_id: customerId,
                    device_id: newDevice.id,
                    device_password: password,
                    probing_history: probingData,
                    accessories: accessories,
                    photos: uploadedUrls.length > 0 ? uploadedUrls : photos,
                    status: ticketStatus,
                    priority: isFastTrack ? 'High' : 'Medium'
                }])
                .select()
                .single();

            if (ticketErr) throw ticketErr;

            // Trigger Print Command
            setTimeout(() => {
                window.print();
                alert(`Ticket Created Successfully! [Ticket ID: ${newTicket.ticket_number}]\nAuto-Assigned to MasterTech: ${isFastTrack ? 'YES' : 'STAGED'}\nSilent Printing Sticker & Claim Slip...`);
                // Reset form
                setPhone('');
                setFullName('');
                setCustomer(null);
                setDevice({ type: 'Laptop', brand: '', model: '', serial: '', color: '' });
                setPassword('');
                setProbing({ occurrence: '', previousRepair: 'No', troubleshooting: '' });
                setFaults([]);
                setAccessories([]);
                setPhotos([]);
                setCsTroubleshooting([]);
            }, 500);

        } catch (error: any) {
            console.error("Intake Error:", error);
            const errMessage = error?.message || error?.details || JSON.stringify(error) || 'Unknown error';
            alert(`Error saving intake: ${errMessage}\nCheck your Supabase RLS Policies!`);
        } finally {
            setIsSaving(false);
        }
    };

    return (
        <div className="max-w-5xl mx-auto p-4 md:p-6 space-y-6 pb-24">
            <TermsModal
                isOpen={showTerms}
                onClose={() => setShowTerms(false)}
                onAgree={handleSubmit}
            />

            <header className="flex justify-between items-center mb-4 text-left">
                <div className="flex items-center gap-4 text-left">
                    <div className="bg-ltt-orange p-3 rounded-2xl text-white shadow-lg shadow-ltt-orange/20"><Laptop size={32} /></div>
                    <div className="text-left">
                        <h1 className="text-3xl font-black uppercase tracking-tight leading-none text-left">Device Intake</h1>
                        <p className="text-text-muted mt-2 font-black text-[10px] uppercase tracking-[0.2em] italic opacity-60 text-left">Professional Diagnostics & Fast-Track Service</p>
                    </div>
                </div>

                <div className="flex gap-2 text-left">
                    <button
                        onClick={() => setIsFastTrack(!isFastTrack)}
                        className={`px-6 py-3 rounded-xl border flex items-center gap-2 transition-all font-black text-xs uppercase tracking-widest ${isFastTrack ? 'bg-red-500 border-red-500 text-white shadow-xl shadow-red-500/20 scale-105' : 'bg-white/5 border-glass-border text-text-muted hover:border-red-500/50 hover:text-red-400'}`}
                    >
                        {isFastTrack ? <HeartPulse size={16} className="animate-pulse" /> : <ShieldCheck size={16} />}
                        {isFastTrack ? 'FAST-TRACK (DEAD UNIT)' : 'Diagnostic Mode'}
                    </button>
                </div>
            </header>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 text-left">
                <div className="lg:col-span-2 space-y-6 text-left">
                    {/* FAST TRACK WARNING */}
                    <AnimatePresence>
                        {isFastTrack && (
                            <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="p-6 bg-red-500/10 border-l-4 border-red-500 rounded-lg space-y-3 mb-6 text-left">
                                <h3 className="text-red-500 font-black uppercase flex items-center gap-2 text-left">
                                    <AlertCircle size={20} /> MasterTech Fast-Track Active
                                </h3>
                                <p className="text-sm text-text-muted font-medium text-left">Unit is marked as **DEAD** or failed preliminary diagnostics. This ticket will be assigned directly to Expert L3/MasterTech.</p>
                            </motion.div>
                        )}
                    </AnimatePresence>

                    {/* CS TROUBLESHOOTING CHECKLIST */}
                    {isFastTrack && (
                        <section className="glass-card p-6 space-y-4 border-l-4 border-ltt-orange overflow-hidden text-left">
                            <h2 className="text-sm font-black uppercase tracking-widest text-ltt-orange flex items-center gap-2 text-left">
                                <RotateCcw size={16} /> CS Best-Practice Troubleshooting
                            </h2>
                            <p className="text-[10px] font-bold text-text-muted italic text-left">Check off what was attempted before dropping off:</p>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-left">
                                {csBestPractices.map(bp => (
                                    <button
                                        key={bp}
                                        onClick={() => toggleItem(setCsTroubleshooting, bp)}
                                        className={`p-3 rounded-lg text-[10px] font-black uppercase border text-left flex items-center justify-between transition-all ${csTroubleshooting.includes(bp) ? 'bg-ltt-orange border-ltt-orange text-white' : 'border-glass-border text-text-muted hover:bg-white/5'}`}
                                    >
                                        {bp}
                                        {csTroubleshooting.includes(bp) && <ShieldCheck size={12} />}
                                    </button>
                                ))}
                            </div>
                        </section>
                    )}

                    {/* CUSTOMER SECTION */}
                    <section className="glass-card p-6 space-y-4 text-left">
                        <h2 className="text-sm font-black uppercase tracking-widest text-ltt-orange flex items-center gap-2 text-left">
                            <Search size={16} /> Customer Lookup
                        </h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-left">
                            <div>
                                <label className="text-[10px] uppercase font-black text-text-muted ml-2">Phone Number</label>
                                <input
                                    className="input-field"
                                    placeholder="09XX-XXX-XXXX"
                                    value={phone}
                                    onChange={(e) => setPhone(e.target.value)}
                                    onBlur={handleLookup}
                                />
                            </div>
                            <div>
                                <label className="text-[10px] uppercase font-black text-text-muted ml-2">Full Name</label>
                                <div className="flex gap-2">
                                    <input
                                        className="input-field flex-1"
                                        placeholder="Customer Name..."
                                        value={fullName}
                                        onChange={(e) => setFullName(e.target.value)}
                                    />
                                    {!customer && fullName && phone.length > 5 && (
                                        <button className="bg-white/5 text-ltt-orange px-3 rounded-lg border border-glass-border hover:bg-ltt-orange/10 transition-colors" title="New Customer Detected">
                                            <UserPlus size={18} />
                                        </button>
                                    )}
                                </div>
                            </div>
                        </div>
                        {customer && (
                            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="p-4 bg-green-500/10 border-l-4 border-green-500 rounded-r-lg text-left">
                                <p className="text-[10px] font-black uppercase text-green-500 tracking-widest flex items-center gap-2"><ShieldCheck size={14} /> EXISITNG RECORD FOUND</p>
                                <p className="font-bold text-lg mt-1 text-white">{customer.full_name}</p>
                                <p className="text-text-muted text-sm">{customer.phone}</p>
                            </motion.div>
                        )}
                    </section>

                    {/* PROBING & SECURITY */}
                    <section className="glass-card p-6 space-y-4 border-l-4 border-accent-blue text-left">
                        <h2 className="text-sm font-black uppercase tracking-widest text-accent-blue flex items-center gap-2 text-left">
                            <ClipboardCheck size={16} /> Probing & Security
                        </h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-left">
                            <div className="text-left">
                                <label className="text-[10px] uppercase font-black text-text-muted ml-2 text-left">Device Password / PIN</label>
                                <div className="relative text-left">
                                    <Lock className="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted" size={14} />
                                    <input className="input-field pl-9 font-mono text-sm" placeholder="Ask customer for password..." value={password} onChange={e => setPassword(e.target.value)} />
                                </div>
                            </div>
                            <div className="text-left">
                                <label className="text-[10px] uppercase font-black text-text-muted ml-2 text-left">When did the issue start?</label>
                                <input className="input-field text-sm" placeholder="e.g. Yesterday after update..." value={probing.occurrence} onChange={e => setProbing({ ...probing, occurrence: e.target.value })} />
                            </div>
                        </div>
                        <div className="space-y-3 text-left">
                            <label className="text-[10px] uppercase font-black text-text-muted ml-2 text-left">Previous Technician Access?</label>
                            <div className="flex gap-2 text-left">
                                {['No', 'Yes - Unauthorized', 'Yes - Official Center'].map(opt => (
                                    <button
                                        key={opt}
                                        onClick={() => setProbing({ ...probing, previousRepair: opt })}
                                        className={`flex-1 py-2 rounded-lg text-[10px] font-black uppercase border transition-all text-center ${probing.previousRepair === opt ? 'bg-accent-blue border-accent-blue text-white shadow-lg shadow-accent-blue/20' : 'border-glass-border text-text-muted hover:bg-white/5'}`}
                                    >
                                        {opt}
                                    </button>
                                ))}
                            </div>
                        </div>
                        <div className="text-left">
                            <label className="text-[10px] uppercase font-black text-text-muted ml-2 text-left">Basic troubleshooting done?</label>
                            <textarea className="input-field text-sm min-h-[80px]" placeholder="e.g. Tried hard reset, different charger..." value={probing.troubleshooting} onChange={e => setProbing({ ...probing, troubleshooting: e.target.value })} />
                        </div>
                    </section>

                    {/* DEVICE TYPE SELECTOR */}
                    <section className="glass-card p-6 space-y-4 text-left">
                        <h2 className="text-sm font-black uppercase tracking-widest text-ltt-orange text-left">Device Category</h2>
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-left">
                            {deviceTypes.map(t => (
                                <button
                                    key={t.name}
                                    onClick={() => setDevice({ ...device, type: t.name })}
                                    className={`flex flex-col items-center justify-center p-4 rounded-xl border transition-all gap-2 text-center ${device.type === t.name ? 'border-ltt-orange bg-ltt-orange/10 text-ltt-orange shadow-lg shadow-ltt-orange/10' : 'border-glass-border text-text-muted grayscale opacity-60'
                                        }`}
                                >
                                    {t.icon}
                                    <span className="text-xs font-black uppercase">{t.name}</span>
                                </button>
                            ))}
                        </div>
                    </section>

                    {/* DEVICE SPECS */}
                    <section className="glass-card p-6 space-y-4 text-left">
                        <h2 className="text-sm font-black uppercase tracking-widest text-ltt-orange text-left">Specifications</h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 text-left">
                            <div className="text-left">
                                <label className="text-[10px] uppercase font-black text-text-muted ml-2 text-left">Brand</label>
                                <input className="input-field" placeholder="Brand" value={device.brand} onChange={e => setDevice({ ...device, brand: e.target.value })} />
                            </div>
                            <div className="text-left">
                                <label className="text-[10px] uppercase font-black text-text-muted ml-2 text-left">Model</label>
                                <input className="input-field" placeholder="Model" value={device.model} onChange={e => setDevice({ ...device, model: e.target.value })} />
                            </div>
                            <div className="text-left">
                                <label className="text-[10px] uppercase font-black text-text-muted ml-2 text-left">Serial Number</label>
                                <input className="input-field font-mono" placeholder="S/N" value={device.serial} onChange={e => setDevice({ ...device, serial: e.target.value })} />
                            </div>
                            <div className="text-left">
                                <label className="text-[10px] uppercase font-black text-text-muted ml-2 text-left">Color</label>
                                <input className="input-field" placeholder="Color" value={device.color} onChange={e => setDevice({ ...device, color: e.target.value })} />
                            </div>
                        </div>
                    </section>

                    {/* ISSUE CHECKLIST */}
                    <section className="glass-card p-6 space-y-4 text-left">
                        <h2 className="text-sm font-black uppercase tracking-widest text-ltt-orange text-left">Issue / Fault Reporting</h2>
                        <div className="flex flex-wrap gap-2 text-left">
                            {commonFaults.map(f => (
                                <button
                                    key={f}
                                    onClick={() => toggleItem(setFaults, f)}
                                    className={`px-4 py-2 rounded-lg text-xs font-bold border transition-all text-center ${faults.includes(f) ? 'bg-ltt-orange border-ltt-orange text-white' : 'border-glass-border text-text-muted'
                                        }`}
                                >
                                    {f}
                                </button>
                            ))}
                        </div>
                        <div className="flex gap-2 text-left">
                            <input className="input-field text-sm" placeholder="Other Issues..." value={otherFault} onChange={e => setOtherFault(e.target.value)} />
                            <button onClick={() => { if (otherFault) { setFaults([...faults, otherFault]); setOtherFault(''); } }} className="btn-primary p-2 px-4 shadow-none"><Plus size={18} /></button>
                        </div>
                    </section>

                    {/* ACCESSORIES CHECKLIST */}
                    <section className="glass-card p-6 space-y-4 text-left">
                        <h2 className="text-sm font-black uppercase tracking-widest text-ltt-orange text-left">Accessories Included</h2>
                        <div className="flex flex-wrap gap-2 text-left">
                            {commonAccessories.map(a => (
                                <button
                                    key={a}
                                    onClick={() => toggleItem(setAccessories, a)}
                                    className={`px-4 py-2 rounded-lg text-xs font-bold border transition-all text-center ${accessories.includes(a) ? 'bg-accent-blue border-accent-blue text-white' : 'border-glass-border text-text-muted'
                                        }`}
                                >
                                    {a}
                                </button>
                            ))}
                        </div>
                        <div className="flex gap-2 text-left">
                            <input className="input-field text-sm" placeholder="Add Accessory (e.g. Case, Stylo)..." value={customAccessory} onChange={e => setCustomAccessory(e.target.value)} />
                            <button onClick={() => { if (customAccessory) { setAccessories([...accessories, customAccessory]); setCustomAccessory(''); } }} className="bg-accent-blue p-2 px-4 text-white rounded-lg"><Plus size={18} /></button>
                        </div>
                    </section>

                    {/* PHOTO CAPTURE */}
                    <section className="glass-card p-6 space-y-4 text-left">
                        <div className="flex justify-between items-center text-left">
                            <h2 className="text-sm font-black uppercase tracking-widest text-ltt-orange text-left">Condition Photos</h2>
                            <button onClick={takePhoto} className="flex items-center gap-2 text-xs font-black text-ltt-orange border border-ltt-orange/50 px-4 py-2 rounded-lg hover:bg-ltt-orange/10 transition-all uppercase">
                                <Camera size={16} /> Capture Image
                            </button>
                        </div>
                        <div className="grid grid-cols-3 md:grid-cols-5 gap-3 text-left">
                            <AnimatePresence>
                                {photos.map((url, i) => (
                                    <motion.div key={i} layout initial={{ scale: 0 }} animate={{ scale: 1 }} exit={{ scale: 0 }} className="relative aspect-square rounded-lg overflow-hidden border border-glass-border group text-left">
                                        <img src={url} className="w-full h-full object-cover" alt="Condition" />
                                        <button onClick={() => removePhoto(i)} className="absolute top-1 right-1 bg-red-500 text-white p-1 rounded-full opacity-0 group-hover:opacity-100 transition-opacity">
                                            <X size={12} />
                                        </button>
                                    </motion.div>
                                ))}
                            </AnimatePresence>
                            {photos.length === 0 && (
                                <div className="aspect-square rounded-xl border border-dashed border-glass-border flex flex-col items-center justify-center text-text-muted opacity-30 text-center">
                                    <Camera size={24} />
                                    <span className="text-[8px] font-black uppercase mt-2">No Images</span>
                                </div>
                            )}
                        </div>
                    </section>
                </div>

                {/* SIDEBAR PREVIEW SECTION */}
                <div className="space-y-6 lg:sticky lg:top-8 h-fit text-left">
                    <div className="glass-card p-6 bg-white/5 border-ltt-orange/30 space-y-6 shadow-2xl text-left">
                        <header className="flex flex-col items-center gap-1 border-b border-glass-border pb-3 text-center">
                            <h2 className="text-xs font-black uppercase tracking-[0.2em] text-ltt-orange">Silent Print Queue</h2>
                            <p className="text-[8px] font-bold text-text-muted uppercase italic">Hardware: P2 & PT-210</p>
                        </header>

                        {/* P2 Sticker Preview */}
                        <div className="space-y-4 text-left">
                            <div className="flex justify-between items-center px-1 text-left">
                                <p className="text-[10px] font-black uppercase text-text-muted opacity-60 text-left">P2 Thermal Preview (Internal Tag)</p>
                                <button
                                    onClick={() => window.print()}
                                    className="p-2 bg-ltt-orange/10 text-ltt-orange rounded-lg hover:bg-ltt-orange hover:text-white transition-all pointer-events-auto z-50 shadow-lg shadow-ltt-orange/10"
                                >
                                    <Printer size={16} />
                                </button>
                            </div>

                            {/* Hidden target for printing */}
                            <div id="thermal-print-target" className="hidden print:block">
                                <ThermalLabel
                                    data={{
                                        ticketNumber: tempTicketId,
                                        customerName: fullName || 'Guest',
                                        customerPhone: phone || 'N/A',
                                        deviceBrand: device.brand,
                                        deviceModel: device.model,
                                        serialNumber: device.serial,
                                        issue: faults.join(', ') || 'No specific fault listed',
                                        date: new Date().toLocaleDateString(),
                                        type: 'Internal'
                                    }}
                                />
                            </div>

                            <div className="mx-auto scale-90 origin-top text-left">
                                <ThermalLabel
                                    data={{
                                        ticketNumber: 'PREVIEW',
                                        customerName: fullName || 'N/A',
                                        customerPhone: phone || 'N/A',
                                        deviceBrand: device.brand,
                                        deviceModel: device.model,
                                        serialNumber: device.serial,
                                        issue: faults.length > 0 ? faults.join(', ') : 'Diagnosis required',
                                        date: new Date().toLocaleDateString(),
                                        type: 'Internal'
                                    }}
                                />
                            </div>
                        </div>

                        {/* PT-210 Claim Slip Preview */}
                        {(isFastTrack || fullName || phone) && (
                            <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} className="space-y-4 pt-6 border-t border-dashed border-glass-border text-left">
                                <div className="flex justify-between items-center px-1 text-left">
                                    <p className="text-[10px] font-black uppercase text-accent-blue opacity-60 text-left">Claim Preview (Customer Slip)</p>
                                </div>
                                <div className="mx-auto scale-90 origin-top text-left">
                                    <ThermalLabel
                                        data={{
                                            ticketNumber: tempTicketId,
                                            customerName: fullName || 'Valued Customer',
                                            customerPhone: phone || '09XX-XXX-XXXX',
                                            deviceBrand: device.brand,
                                            deviceModel: device.model,
                                            serialNumber: device.serial,
                                            issue: 'Hardware assessment triggered',
                                            date: new Date().toLocaleDateString(),
                                            type: 'Claim'
                                        }}
                                    />
                                </div>
                            </motion.div>
                        )}

                        <div className="space-y-4 pt-6 border-t border-glass-border text-left">
                            <div className="flex items-center justify-between px-2 text-left">
                                <span className="text-xs font-black uppercase text-text-muted text-left">Print Copies:</span>
                                <div className="flex items-center gap-4 text-left">
                                    <button onClick={() => setStickerCount(Math.max(1, stickerCount - 1))} className="p-2 bg-white/5 rounded-lg hover:text-ltt-orange transition-colors"><Minus size={14} /></button>
                                    <span className="text-xl font-black">{stickerCount}</span>
                                    <button onClick={() => setStickerCount(stickerCount + 1)} className="p-2 bg-white/5 rounded-lg hover:text-ltt-orange transition-colors"><Plus size={14} /></button>
                                </div>
                            </div>
                            <button
                                onClick={() => setShowTerms(true)}
                                disabled={isSaving}
                                className={`w-full py-5 flex items-center justify-center gap-3 text-lg font-black shadow-lg transition-all rounded-xl ${isFastTrack ? 'bg-red-500 text-white shadow-red-500/20 hover:scale-[1.02]' : 'btn-primary shadow-ltt-orange/40'}`}
                            >
                                {isSaving ? 'Registering...' : <><Save size={24} /> {isFastTrack ? 'Confirm Drop-off (Live Save)' : 'Confirm Intake (Live Save)'}</>}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default IntakePage;
